name: love2code
num_bands: 14
band_size: 8
ngram_size: 5
tokenizer_str: p50k
num_sig_chunks: 128
num_docs: 3000000000
max_lines_per_path: 1000000
content_key: text
local_input: /mnt/raid0/love2code_input
working_dir: /mnt/raid0/working
output_dir: /mnt/raid0/love2code_output
remote_input: s3://ai2-llm/pretraining-data/sources/learn2code/love2code-baseline-filtered-20250218_004/
remote_working_dir: null
remote_output: null
concat_key: 
  - metadata.repo_name
  - metadata.language
  