"""
Some internal helpers to read the internal files generated by the rust code. 
Think of this as a debugging tool/inspector 
"""

import glob
import json
import os
import struct
from collections import defaultdict

import yaml
from smart_open import open
from tqdm.auto import tqdm

# =====================================================
# =                  CONFIG PARSEY STUFF              =
# =====================================================


MAX_U64 = (1 << 64) - 1


def to_byte_size(n):
    assert isinstance(n, int)
    return max(1, (n.bit_length() + 7) // 8)


def compute_sig_size(n):
    n_choose_2 = (n * (n - 1)) // 2
    return max(1, (n_choose_2.bit_length() + 7) // 8)


def unpack_u64le(b):
    return struct.unpack("<Q", b)[0]


def read_intX(bytestring):
    result = 0
    for b in bytestring:
        result = (result << 8) | b
    return result


def get_sizes(storage_dir, config):
    # Assumes that the values in the config are the true ones (and have not been overridden)
    try:
        config_data = yaml.safe_load(open(config, "r"))
    except:
        config_data = {}

    max_lines_per_path = config_data.get("eng_params", {}).get(
        "max_lines_per_path", 1_000_000_000
    )
    num_docs = config_data.get("eng_params", {}).get("num_docs", 1_000_000_000)

    file_map_loc = os.path.join(storage_dir, "filemap.json.gz")
    file_map = json.loads(open(file_map_loc, "rb").read())

    path_size = to_byte_size(len(file_map["indices"]))
    line_size = to_byte_size(max_lines_per_path)
    sig_size = compute_sig_size(num_docs)

    return path_size, line_size, sig_size


# =====================================================
# =                  SIGNATURE READER                 =
# =====================================================


def read_all_sig_files(storage_dir, config):
    # Returns a list of (band_id, path_id, line_num, signature)
    sig_dir = os.path.join(storage_dir, "sig_storage")
    files = glob.glob(os.path.join(sig_dir, "**/*.sig.bin"), recursive=True)
    all_data = []
    for f in tqdm(files):
        band_id = os.path.basename(os.path.dirname(os.path.dirname(f))).split("_")[-1]
        for tup in read_signature_file(f, storage_dir, config):
            all_data.append((band_id,) + tup)
    return all_data


def read_signature_file(sig_file, storage_dir, config):
    # Returns a list of (path_id, line_num, signature)
    data = open(sig_file, "rb").read()

    path_size, line_size, sig_size = get_sizes(storage_dir, config)
    output = []
    for i in range(0, len(data), path_size + line_size + sig_size):
        chunk = data[i : i + path_size + line_size + sig_size]
        signature = read_intX(chunk[:sig_size])
        path_id = read_intX(chunk[sig_size : sig_size + path_size])
        line_id = read_intX(chunk[sig_size + path_size :])
        output.append((path_id, line_id, signature))
    return output


# =====================================================
# =                  READ EDGE STUFF                  =
# =====================================================


def read_all_edge_files(storage_dir, config):
    edge_dir = os.path.join(storage_dir, "edges")
    files = glob.glob(os.path.join(edge_dir, "**/*.edges.bin"), recursive=True)
    all_data = []
    for f in tqdm(files):
        all_data.extend(read_edge_file(f, storage_dir, config))
    return all_data


def read_edge_file(edge_file, storage_dir, config):
    path_size, line_size, _ = get_sizes(storage_dir, config)
    data = open(edge_file, "rb").read()

    pairlen = path_size + line_size
    max_path = 1 << path_size - 1
    max_line = 1 << line_size - 1

    edges = []
    cur_group = []
    for i in range(0, len(data), path_size + line_size):
        chunk = data[i : i + path_size + line_size]
        path_id = read_intX(chunk[:path_size])
        line_id = read_intX(chunk[path_size:])

        if (path_id, line_id) == (max_path, max_line):
            edges.append(cur_group)
            cur_group = []
        else:
            cur_group.append((path_id, line_id))

    return edges


# =====================================================
# =                   READ CC STUFF                   =
# =====================================================


def read_clean_file(clean_file):
    data = open(clean_file, "rb").read()
    metadata = [unpack_u64le(data[i * 8 : i * 8 + 8]) for i in range(5)]
    entry_size = sum(metadata)

    path_size, line_size, cc_id_size, cc_size = (
        metadata[0],
        metadata[1],
        metadata[2],
        metadata[3],
    )

    entries = [data[i : i + entry_size] for i in range(40, len(data), entry_size)]

    def parse_entry(entry):
        path_num = read_intX(entry[:path_size])
        line_num = read_intX(entry[path_size : path_size + line_size])
        cc_id = read_intX(
            entry[path_size + line_size : path_size + line_size + cc_id_size]
        )
        cc_mag = read_intX(
            entry[
                path_size
                + line_size
                + cc_id_size : path_size
                + line_size
                + cc_id_size
                + cc_size
            ]
        )
        cc_idx = read_intX(entry[-cc_size:])
        return (path_num, line_num, cc_id, cc_mag, cc_idx)

    return [parse_entry(entry) for entry in entries]


# =====================================================
# =                   READ TRUE JACC VALUES           =
# =====================================================


def read_true_jacccards(jacc_file):
    return json.loads(open(jacc_file, "rb").read())
