# Note that we leave cluster_name blank, so that it will be filled in by the CLI.

min_workers: 1
max_workers: 200
upscaling_speed: 5.0

docker:
  image: "public.ecr.aws/anyscale/ray:2.35.0-slim"
  container_name: "ray_container"
  pull_before_run: True
  run_options:
    - --ulimit nofile=65535:65535
idle_timeout_minutes: 60
provider:
  type: aws
  region: us-east-1
  cache_stopped_nodes: False
  use_internal_ips: True
auth:
  ssh_private_key: ~/.ssh/ray-autoscaler-v1-east.pem
  ssh_user: ubuntu
available_node_types:
  head_default:
    resources: {"CPU": 0}
    node_config:
      KeyName: ray-autoscaler-v1-east
      InstanceType: i4i.32xlarge
      ImageId: ami-085ad6ae776d8f09c
      IamInstanceProfile:
        Arn: arn:aws:iam::896129387501:instance-profile/ray-worker-v1
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 150
            VolumeType: gp3
      TagSpecifications:
        - ResourceType: instance
          Tags:
            - Key: Project
              Value: oe-data      


  worker_i4i_32xl:
    min_workers: 0
    max_workers: 16
    resources: {"CPU": 0}
    node_config:
      KeyName: ray-autoscaler-v1-east
      InstanceType: i4i.32xlarge
      ImageId: ami-085ad6ae776d8f09c
      IamInstanceProfile:
        Arn: arn:aws:iam::896129387501:instance-profile/ray-worker-v1
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 150
            VolumeType: gp3
      TagSpecifications:
        - ResourceType: instance
          Tags:
            - Key: Project
              Value: oe-data      


  # worker_m7_4xl:
  #   min_workers: 0
  #   max_workers: 50
  #   node_config:
  #     KeyName: ray-autoscaler-v1-east
  #     InstanceType: m7i.4xlarge
  #     ImageId: ami-0dd6adfad4ad37eec
  #     IamInstanceProfile:
  #       Arn: arn:aws:iam::896129387501:instance-profile/ray-worker-v1
  #     # InstanceMarketOptions:
  #     #   MarketType: spot
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/sda1
  #         Ebs:
  #           VolumeSize: 500
  #           VolumeType: io2
  #           Iops: 7500
  #     TagSpecifications:
  #       - ResourceType: instance
  #         Tags:
  #           - Key: Project
  #             Value: oe-data

  # worker_m7_8xl:
  #   min_workers: 0
  #   max_workers: 100
  #   node_config:
  #     KeyName: ray-autoscaler-v1-east
  #     InstanceType: m7i-flex.8xlarge
  #     ImageId: ami-0dd6adfad4ad37eec
  #     IamInstanceProfile:
  #       Arn: arn:aws:iam::896129387501:instance-profile/ray-worker-v1
  #     InstanceMarketOptions:
  #       MarketType: spot
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/sda1
  #         Ebs:
  #           VolumeSize: 150
  #           VolumeType: gp3
  #     TagSpecifications:
  #       - ResourceType: instance
  #         Tags:
  #           - Key: Project
  #             Value: oe-data


  # worker_m7_12xl:
  #   min_workers: 0
  #   max_workers: 10
  #   node_config:
  #     KeyName: ray-autoscaler-v1-east
  #     InstanceType: m7i.12xlarge
  #     ImageId: ami-0dd6adfad4ad37eec
  #     IamInstanceProfile:
  #       Arn: arn:aws:iam::896129387501:instance-profile/ray-worker-v1
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/sda1
  #         Ebs:
  #           VolumeSize: 500
  #           VolumeType: gp3
  #     TagSpecifications:
  #       - ResourceType: instance
  #         Tags:
  #           - Key: Project
  #             Value: oe-data

  # worker_m7i_16xl:
  #   min_workers: 0
  #   max_workers: 10
  #   node_config:
  #     KeyName: ray-autoscaler-v1-east
  #     InstanceType: m7i.16xlarge
  #     ImageId: ami-0dd6adfad4ad37eec
  #     IamInstanceProfile:
  #       Arn: arn:aws:iam::896129387501:instance-profile/ray-worker-v1
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/sda1
  #         Ebs:
  #           VolumeSize: 500
  #           VolumeType: gp3
  #     TagSpecifications:
  #       - ResourceType: instance
  #         Tags:
  #           - Key: Project
  #             Value: oe-data


head_node_type: head_default
file_mounts: {
  "/home/ray/pyproject.toml":"pyproject.toml",
  "/home/ray/setup.py":"setup.py",
  "/home/ray/src/mise_en_ray/__init__.py":"src/mise_en_ray/__init__.py"
}
cluster_synced_files: []
rsync_exclude:
  - "**/.git"
  - "**/.git/**"
rsync_filter:
  - ".gitignore"

# WARNING: These run on the host OS, not inside the ray container.
initialization_commands:
  - sudo pkill -9 apt-get || true && sudo pkill -9 dpkg || true
  - sudo bash -c 'rm -rf /etc/security/limits.d; echo "* soft nofile 65535" >> /etc/security/limits.conf; echo "* hard nofile 65535" >> /etc/security/limits.conf;'

# WARNING: These run INSIDE the ray container, not on the host OS.
setup_commands:
  - sudo bash -c 'rm -rf /etc/security/limits.d; echo "* soft nofile 65535" >> /etc/security/limits.conf; echo "* hard nofile 65535" >> /etc/security/limits.conf;'
  - sudo apt-get update -y && export DEBIAN_FRONTEND=noninteractive && sudo apt-get -y install curl build-essential awscli git
  - sudo chmod 777 src
  - pip install uv --upgrade
  - uv pip install -e .
  - export RAY_DEDUP_LOGS=0
  - sudo yum list installed mdadm &>/dev/null || sudo yum install mdadm -y
  - sudo mdadm --detail /dev/md0 &>/dev/null || sudo mdadm --create /dev/md0 --level=0 --raid-devices=8 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1 /dev/nvme4n1 /dev/nvme5n1 /dev/nvme6n1 /dev/nvme7n1 /dev/nvme8n1
  - sudo blkid /dev/md0 | grep -q xfs || sudo mkfs.xfs /dev/md0
  - sudo mkdir -p /mnt/raid0
  - mountpoint -q /mnt/raid0 || sudo mount /dev/md0 /mnt/raid0
  - sudo chown -R "$USER" /mnt/raid0  
  - sudo yum install mdadm -y
  - sudo mdadm --create /dev/md0 --level=0 --raid-devices=8 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1 /dev/nvme4n1 /dev/nvme5n1 /dev/nvme6n1 /dev/nvme7n1 /dev/nvme8n1 
  - sudo mkfs.xfs /dev/md0
  - sudo mkdir /mnt/raid0
  - sudo mount /dev/md0 /mnt/raid0
  - sudo chown -R $USER /mnt/raid0
  - sudo yum install gcc -y
  - sudo yum install cmake -y
  - sudo yum install openssl-devel -y
  - sudo yum install g++ -y
  - sudo yum install htop -y
  - aws configure set default.region us-east-1
  - wget https://github.com/peak/s5cmd/releases/download/v2.2.2/s5cmd_2.2.2_Linux-64bit.tar.gz 
  - tar -xvzf s5cmd_2.2.2_Linux-64bit.tar.gz 
  - git clone https://github.com/revbucket/minhash-rs.git
  - cd minhash-rs
  - git checkout refac2025 
  - cargo build --release

  

head_setup_commands: []
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
head_start_ray_commands:
  - ray stop
  - RAY_DEDUP_LOGS=0 ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host=0.0.0.0

# Command to start ray on worker nodes. You don't need to change this.
worker_start_ray_commands:
  - ray stop
  - RAY_DEDUP_LOGS=0 ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076