// External crates
use clap::{Parser, Subcommand};

// Standard library
use std::option::Option;
use std::path::PathBuf;

// Internal crate imports
use crate::exact_dedup_disk::{exact_dedup_disk_group, exact_dedup_disk_prune};
use crate::exact_dedup_memory::exact_dedup_memory;
use crate::minhash_disk::{
    mh_build_file_map, mh_build_uf, mh_clean_files, mh_gather_edges, mh_hash_docs,
};
use crate::minhash_memory::minhash_memory;

pub mod exact_dedup_disk;
pub mod exact_dedup_memory;
pub mod minhash_base;
pub mod minhash_config;
pub mod minhash_disk;
pub mod minhash_memory;
pub mod storage;
pub mod uf_rush2;
pub mod utils;

/* 4 basic use cases here:
{Exact, Fuzzy} x {Memory, Disk} deduplication:

Exact vs Fuzzy(minhash) Deduplication:
- Exact deduplication only keeps _one_ copy of a particular document, according to an either prespecified
  identifying field (i.e. a hash of the text), or will hash the text itself.
- Fuzzy deduplication using minhash performs minhash according to this schema: https://arxiv.org/abs/2107.06499
  More details on how this works in minhash.rs

Memory or Disk-based settings:
- In the memory-based settings, the necessary intermediate data structures are stored in memory. This use case
  is good for when the dataset you're deduplicating is relatively small. This should be plug-n-play and does not
  require careful system setup.
- In the disk-based setting: the intermediate data structures are stored on disk. This is useful for when the
  dataset is large and distributed processing is needed. See the README/tutorials for these large-scale jobs.
*/

/*
New plan:
It helps to consider minHash in phases:

Phase 1: Look at all the file paths we want to run minHash dedup on and rename them
         with usize identifiers. Store this in a FileMap structure.
         In this way, all documents are now uniquely identified by their
         (path_id, line_num)

Phase 2: Compute (band_id, signature, doc_id) for every document.
         This is the heavy minhashing step, but can be parallelized
         across chunks over the paths.

         Essentially this works as follows -- for each path
         we loop over documents and compute it's minhash signatures.
         We compute band_size * num_bands signatures, and then hash
         the signature across each band (rows in the pic below).
         If any two documents share the same (band_id, siganture), then
         they are duplicates.

                        Band Size
             ----------------------------
            |                            |
            |                            |
      Bands |                            |
            |                            |
            |                            |
            ------------------------------


Phase 3: Collect edges, linking all the documents that share the same
         (band_id, siganture) together. Store these in a separate set of files.

Phase 4: Combine all the edges and build a GLOBAL union find data structure and
         use this to collect connected components. Store both these connected
         components (for later examination), and collect the lines that should
         be removed from the dataset (grouped by path_chunk, so they can be pruned
         in a multinode setting)

Phase 5: Clean the duplicate documents from the paths. Phase 4 tells us which
         lines of each path should be removed.


(
Auxiliary phase: For examination purposes, we can look at each connected component
                  and get stats on the true pairwise jaccard similarity between
                  documents marked as "duplicates"
)

----------------
Some design notes:

+ Config: Globally, this requires a json config. I'll make an example when
          I square up exactly what I need here.

+ Disk space: We rely heavily on storing auxiliary data structures on disk.
              Basically there's a state change after every phase where we make
              some new files after every phase. I'll build some python code
              to read these for debuggy purposes later (TBD). Each section
              will describe the file structure and contents in comments below.

+ Parallelism: Phase 3 and phase 4 need to be done globally (unfortunately,
               there's no avoiding at least one global step). Phase 1 only
               really needs access to the filenames but is very cheap.
               Phase 2, 4, and 5 are the heavy steps and can be done across
               file parallelism. This would require some coordination with the
               global data structures generated by phase 3 and 4.

+ s3: We don't touch s3 in rust. I have yet to find a package that works
      reliably, so let's just assume that all interaction between the LFS
      and s3 is done outside the context of this rust code


+ Input path structure: For simplicity, we require that the input paths all
                        live in one directory and have unique basenames.


+ One fell swoop: if your dataset is small enough that you just want to do
                  all phases in one command, use `min-hash`
*/

/*=================================================================
=                                  ARGS                           =
=================================================================*/

#[derive(Parser)]
#[clap(author, version, about, long_about = None)]
struct ArgParser {
    #[clap(subcommand)]
    command: Commands,

    #[arg(long, default_value_t = 0)]
    threads: usize,
}

#[derive(Subcommand, Debug)]
enum Commands {
    #[clap(arg_required_else_help = true)]
    /*============================================================
    =            Exact Deduplication Methods                     =
    ============================================================*/

    /// Memory-based exact deduplication
    ExactDedupMemory {
        #[arg(required = true, long)]
        input_dir: PathBuf,

        #[arg(required = true, long)]
        output_dir: PathBuf,

        #[arg(long, default_value_t=String::from("text"))]
        text_key: String,

        #[arg(long)]
        /// If present, will be the ID used for exact deduplication.
        hash_key: Option<String>,

        #[arg(long, default_value_t = 128)]
        /// If ^ not present, will be the number of bits used for hashing
        hash_bits: usize,

        #[arg(long)]
        /// If present, we don't actually delete and just put the
        /// Can be a nested key, like "metadata.exact_duplicates" => {metadata : {exact_duplicates: {...}}}
        annotate_key: Option<String>,
    },

    /// Disk-based exact deduplication (step 1 of 2)
    ExactDedupDiskGroup {
        #[arg(required = true, long)]
        input_dir: PathBuf,

        #[arg(required = true, long)]
        storage_dir: PathBuf,

        #[arg(long, default_value_t=String::from("text"))]
        text_key: String,

        #[arg(long, required = true)]
        /// If present, will be the ID used for exact deduplication.
        hash_key: String,

        #[arg(long, default_value_t = 128)]
        /// If ^ not present, will be the number of bits used for hashing
        hash_bits: usize,

        #[arg(long, required = true)]
        /// How many bins/groups the docs get hashed into
        num_bins: usize,
    },

    /// Disk-based exact deduplication (step 2 of 2)
    ExactDedupDiskPrune {
        #[arg(required = true, long)]
        storage_dir: PathBuf,

        #[arg(required = true, long)]
        output_dir: PathBuf,

        #[arg(required = true, long)]
        hash_key: String,

        #[arg(long)]
        /// If present, we don't actually delete and just put the
        /// Can be a nested key, like "metadata.exact_duplicates" => {metadata : {exact_duplicates: {...}}}
        annotate_key: Option<String>,
    },

    /*============================================================
    =            MinHash Deduplication Methods                   =
    ============================================================*/
    MinhashMemory {
        #[arg(required = true, long)]
        input_dir: PathBuf,

        #[arg(required = true, long)]
        storage_dir: PathBuf,

        #[arg(required = true, long)]
        output_dir: PathBuf,

        #[arg(long, default_value_t=String::from("text"))]
        text_key: String,

        #[arg(long)]
        config: Option<PathBuf>,

        /// Config overrides -- these should be specified in the config
        #[arg(long)] // Overrides num_buckets for minhash if not specified in config
        num_buckets: Option<usize>,

        #[arg(long)] // Overrides bucket_size for minhash if not specified in config
        bucket_size: Option<usize>,

        #[arg(long)] // Overrides ngram_size for minhash if not specified in config
        ngram_size: Option<usize>,

        #[arg(long)] // Overrides permutation_seeds for minhash if not specified in config
        permutation_seed: Option<u64>,

        #[arg(long)] // Overrides tokenizer type for minhash if not specified in config
        tokenizer: Option<String>,

        #[arg(long)] // Overrides whether we should annotate at the output
        annotate: Option<bool>,

        #[arg(long)] // Overrides what the key
        annotate_key: Option<String>,

        #[arg(long)]
        delete_while_cleaning: Option<bool>,

        #[arg(long)]
        remove_duplicates: Option<bool>,

        #[arg(long, default_value_t = false)]
        cleanup_storage: bool,
    },

    MhBuildFileMap {
        #[arg(required = true, long)]
        input_dir: PathBuf,

        #[arg(required = true, long)]
        storage_dir: PathBuf,
    },

    MhHashDocs {
        #[arg(required = true, long)]
        storage_dir: PathBuf,

        #[arg(long, default_value_t=String::from("text"))]
        text_key: String,

        #[arg(long)]
        config: Option<PathBuf>,

        #[arg(long, required = true)]
        path_chunk: usize,

        #[arg(long, required = true)]
        num_path_chunks: usize,

        /// Config overrides -- these should be specified in the config
        #[arg(long)] // Overrides num_buckets for minhash if not specified in config
        num_buckets: Option<usize>,

        #[arg(long)] // Overrides bucket_size for minhash if not specified in config
        bucket_size: Option<usize>,

        #[arg(long)] // Overrides ngram_size for minhash if not specified in config
        ngram_size: Option<usize>,

        #[arg(long)] // Overrides permutation_seeds for minhash if not specified in config
        permutation_seed: Option<u64>,

        #[arg(long)] // Overrides tokenizer type for minhash if not specified in config
        tokenizer: Option<String>,

        #[arg(long)]
        num_docs: Option<usize>,

        #[arg(long)]
        max_lines_per_path: Option<usize>,

        #[arg(long)]
        num_sig_chunks: Option<usize>,
    },

    MhGatherEdges {
        #[arg(required = true, long)]
        storage_dir: PathBuf,

        #[arg(long)]
        config: Option<PathBuf>,

        #[arg(long)]
        num_docs: Option<usize>,

        #[arg(long)]
        max_lines_per_path: Option<usize>,
    },

    MhBuildUf {
        #[arg(required = true, long)]
        storage_dir: PathBuf,

        #[arg(long)]
        config: Option<PathBuf>,

        #[arg(long, required = true)]
        num_path_chunks: usize,

        #[arg(long)]
        max_lines_per_path: Option<usize>,
    },

    MhCleanFiles {
        #[arg(required = true, long)]
        input_dir: PathBuf,

        #[arg(required = true, long)]
        storage_dir: PathBuf,

        #[arg(required = true, long)]
        output_dir: PathBuf,

        #[arg(required = true, long)]
        path_chunk: usize,

        #[arg(required = true, long)]
        num_path_chunks: usize,

        #[arg(long)]
        config: Option<PathBuf>,

        #[arg(long)] // Overrides whether we should annotate at the output
        annotate: Option<bool>,

        #[arg(long)] // Overrides what the key
        annotate_key: Option<String>,

        #[arg(long)]
        delete_while_cleaning: Option<bool>,

        #[arg(long)]
        remove_duplicates: Option<bool>,

        #[arg(long, default_value_t = false)]
        cleanup_storage: bool,
    },
}

/*=================================================================
=                      PHASE 2: HASH THE PATHS                    =
=================================================================*/
/* MULTINODE PARALLELISM ON PATH CHUNKS:

    This creates the signature files. The signature files are named like:
    working_dir/
    └── signatures/
       └── band_XXX/
           └── sigchunk_YYY/
               └── pathchunk_ZZZ.sig.bin

    Where the:
    - band_id (XXX) ranges from 0..num_bands (specified in the main config)
    - sigchunk_id (YYY) ranges from 0..num_sigchunks (specified in the main config)
    - pathchunk (ZZZ) ranges from 0..num_path_chunks (in the args of this function)


    And the contents of each file is a packing of bits of chunk size dependent on the number
    of paths/maximum_line_size we have. But generally each file contains encoded-then-concatenated
    triples of the form
        `(signature, path_id, line_num)`
    where the exact size of each component can differ based on configs
*/

/*=================================================================
=                      PHASE 3: GATHER EDGES                      =
=================================================================*/
/* MULTINODE PARALLELISM ON BAND_ID
    This creates the edge and singleton files.


    ----- edge files -----
    Edge file naming structure:
    working_dir/
    └── edges/
       └── sigchunk_YYY/
           └── band_XXX.edges.bin

    Where the:
        - band_id (XXX) ranges from 0..num_bands (pulled from signatures files)
        - sigchunk_id (YYY) ranges from 0..num_sigchunks (pulled from signatures files)

    And the contents of each file is a packed-bytes object, where if
    (path_A, line_1) and (path_B, line_2) have the same signature in a single band, then the bytes

        `(path_A, line_1, path_B, line_2)`

    appear in the file.


    ----- singleton file ----
    Singleton file naming structure:
    working_dir/
    └── edges/
       └── singletons.bin

    Where the contents just contain the number of lines per path, encoded as u64's like

        `(path_id, num_lines)`

*/

/*=================================================================
=                      PHASE 4: Build Union Find                  =
=================================================================*/
/* NO MULTINODE PARALLELISM! =(
This creates a union find structure to merge together the edges.
It creates the connected-components files and the kill files

    ----- cc files -----
    working_dir/
    └── ccs/
       └── chunk_ZZZ.cc.bin

    where the chunk (ZZZ) ranges from 0..num_path_chunks and has contents, that when viewed as a single
    array are elements of the form

        `(path_id, line_num)`

    saved as u64's, where there's a special token which is the u64::MAX repeated twice, indicating
    the end of a connected component


    ------ kill files ----
    working_dir/
    └── kill/
       └── chunk_ZZZ.kill.bin

    where the chunk (ZZZ) ranges from 0..num_path_chunks and has contents, that when viewed as a single
    array are is a concatenation of subarrays like

        `[path_id, kill_line_1, kill_line_2, ..., kill_line_N, terminus]`

    where each are u64s and terminus is u64::MAX

    ----- annotate helpers -----
    working_dir/
    └── annotate/
       └── chunk_ZZZ.annotate.bin

    where the chunk (ZZZ) ranges from 0..num_path_chunks and has contents, that when viewd as a single
    array are is a concatenation of subarrays like


*/

/*=================================================================
=                      PHASE 5a: CLEAN DUPLICATES                 =
=================================================================*/
/* MULTINODE PARALLELISM ON PATHS
    This cleans the duplicates out from the data.
    It simply requires the outputs of the previous steps (namely the FileMap in step 1, and the
    .kill.bin files in step 4).

    It will copy over (deduplicated) files from the input_dir to the output_dir (as specified by the config)

*/

/*=================================================================
=                                 MAIN                            =
=================================================================*/

#[allow(unreachable_patterns)]
fn main() {
    let args = ArgParser::parse();
    let threads = args.threads;
    if threads != 0 {
        std::env::set_var("RAYON_NUM_THREADS", threads.to_string());
    }

    let result = match &args.command {
        Commands::ExactDedupMemory {
            input_dir,
            output_dir,
            text_key,
            hash_key,
            hash_bits,
            annotate_key,
        } => exact_dedup_memory(
            input_dir,
            output_dir,
            text_key,
            hash_key.clone(),
            *hash_bits,
            annotate_key.clone(),
        ),

        Commands::ExactDedupDiskGroup {
            input_dir,
            storage_dir,
            text_key,
            hash_key,
            hash_bits,
            num_bins,
        } => exact_dedup_disk_group(
            input_dir,
            storage_dir,
            text_key,
            &hash_key.clone(),
            *hash_bits,
            *num_bins,
        ),

        Commands::ExactDedupDiskPrune {
            storage_dir,
            output_dir,
            hash_key,
            annotate_key,
        } => exact_dedup_disk_prune(storage_dir, output_dir, hash_key, annotate_key),

        Commands::MinhashMemory {
            input_dir,
            storage_dir,
            output_dir,
            text_key,
            config,
            num_buckets,
            bucket_size,
            ngram_size,
            permutation_seed,
            tokenizer,
            annotate,
            annotate_key,
            delete_while_cleaning,
            remove_duplicates,
            cleanup_storage,
        } => minhash_memory(
            input_dir,
            storage_dir,
            output_dir,
            text_key,
            config,
            *num_buckets,
            *bucket_size,
            *ngram_size,
            *permutation_seed,
            tokenizer.clone(),
            annotate.clone(),
            annotate_key.clone(),
            *delete_while_cleaning,
            *remove_duplicates,
            *cleanup_storage,
        ),

        Commands::MhBuildFileMap {
            input_dir,
            storage_dir,
        } => mh_build_file_map(input_dir, storage_dir),

        Commands::MhHashDocs {
            storage_dir,
            text_key,
            config,
            path_chunk,
            num_path_chunks,
            num_buckets,
            bucket_size,
            ngram_size,
            permutation_seed,
            tokenizer,
            num_docs,
            max_lines_per_path,
            num_sig_chunks,
        } => mh_hash_docs(
            storage_dir,
            text_key,
            config,
            *path_chunk,
            *num_path_chunks,
            *num_buckets,
            *bucket_size,
            *ngram_size,
            *permutation_seed,
            tokenizer.clone(),
            *num_docs,
            *max_lines_per_path,
            *num_sig_chunks,
        ),

        Commands::MhGatherEdges {
            storage_dir,
            config,
            num_docs,
            max_lines_per_path,
        } => mh_gather_edges(storage_dir, config, *num_docs, *max_lines_per_path),

        Commands::MhBuildUf {
            storage_dir,
            config,
            num_path_chunks,
            max_lines_per_path,
        } => mh_build_uf(
            storage_dir,
            config.clone(),
            *num_path_chunks,
            *max_lines_per_path,
        ),

        Commands::MhCleanFiles {
            input_dir,
            storage_dir,
            output_dir,
            path_chunk,
            num_path_chunks,
            config,
            annotate,
            annotate_key,
            delete_while_cleaning,
            remove_duplicates,
            cleanup_storage,
        } => mh_clean_files(
            input_dir,
            storage_dir,
            output_dir,
            *path_chunk,
            *num_path_chunks,
            config,
            *annotate,
            annotate_key.clone(),
            *delete_while_cleaning,
            *remove_duplicates,
            *cleanup_storage,
        ),

        _ => Ok(()),
    };
    result.unwrap()
}
